name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Update .NET packages
      run: |
        cd backend
        dotnet list package --outdated
        # Uncomment the following line to auto-update packages
        # dotnet add package System.IO.Ports

    - name: Update npm packages
      run: |
        cd frontend
        npm outdated || true
        # Uncomment the following line to auto-update packages
        # npm update

    - name: Check for vulnerabilities
      run: |
        cd backend
        dotnet list package --vulnerable --include-transitive
        cd ../frontend
        npm audit

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated Dependency Updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates.
          
          Please review the changes carefully before merging.
          
          - [ ] Backend .NET packages updated
          - [ ] Frontend npm packages updated
          - [ ] Security vulnerabilities addressed
        branch: dependency-updates
        delete-branch: true